version: "2"
services:
  # Service for database with MongoDB
  mongodb-poatek:
    image: mongo
    container_name: mongodb-poatek
    ports: 
      - 27017:27017
    networks: 
      - challenge
  # Service for backend with NodeJs
  backend-poatek:
    image: node
    container_name: backend-poatek
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm start"
    depends_on: 
      - mongodb-poatek
    ports: 
      - 3000:3000
    networks: 
      - challenge
  # Service for frontend with AngularJs
  frontend-poatek:
    image: node
    container_name: frontend-poatek
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm start"
    depends_on: 
      - backend-poatek
    ports: 
      - 80:80
    networks: 
      - challenge
networks:
  challenge:
    driver: bridge